### PR TITLE
add ability to delete a resource

### PR DESCRIPTION
**Pull request by thomaxxl**
This change is [Reviewable](https://reviewable.io/reviews/socialwifi/jsonapi-requests/33)

### CODE REVIEW

**Comment by maruqu** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-L0ErTYrIlmmfuGym_fs:-L0ErTYrIlmmfuGym_ft:bjy0omi) (no related file):*
Thanks for your Pull request.  Ability to delete objects is crucial for fully functional JSON API client.
Although your Pull request is lacking some crucial elements to be merged.

We pay attention to have tests that cover every new feature.
Please provide them to enable us to check if the feature is working as expected.

---

*[jsonapi_requests/orm/api_model.py, line 158 at r1](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-L0EtLQtxrpoMby54fWj:-L0EtLQtxrpoMby54fWk:bpg852x) ([raw file](https://github.com/socialwifi/jsonapi-requests/blob/5791b7f1635f588bc3c64572780726ef091779a4/jsonapi_requests/orm/api_model.py#L158)):*
> `endpoint.delete()` does not need to have the object passed as argument

>  response should be properly handled, for example:
    `        if api_response.status_code == 204:
                  self.raw_object = None`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33)*

**Comment by maruqu** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33)*

**Comment by thomaxxl** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-L0ErTYrIlmmfuGym_fs:-L0JFD_8o1YBc4TuK0sI:b-wh9qhh) (no related file):*
> None

---

*[jsonapi_requests/orm/api_model.py, line 158 at r1](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-L0EtLQtxrpoMby54fWj:-L0JFHK5yg7SR_yhy-bO:b-oi8s2n) ([raw file](https://github.com/socialwifi/jsonapi-requests/blob/5791b7f1635f588bc3c64572780726ef091779a4/jsonapi_requests/orm/api_model.py#L158)):*
<details><summary><i>Previously, maruqu (artmruk) wrote…</i></summary><blockquote>

> `endpoint.delete()` does not need to have the object passed as argument

>  response should be properly handled, for example:
    `        if api_response.status_code == 204:
                  self.raw_object = None`
</blockquote></details>

The spec has the following to say regarding deleting resources:
<quote>
Responses
202 Accepted
If a deletion request has been accepted for processing, but the processing has not been completed by the time the server responds, the server MUST return a 202 Accepted status code.

204 No Content
A server MUST return a 204 No Content status code if a deletion request is successful and no content is returned.

200 OK
A server MUST return a 200 OK status code if a deletion request is successful and the server responds with only top-level meta data.

404 NOT FOUND
A server SHOULD return a 404 Not Found status code if a deletion request fails due to the resource not existing.

Other Responses
A server MAY respond with other HTTP status codes.

A server MAY include error details with error responses.

A server MUST prepare responses, and a client MUST interpret responses, in accordance with HTTP semantics. 
</quote>


Not sure what I should do in case of a 202 either
I may do something like this:

```
def delete(self):
        api_response = self.endpoint.delete(object=self.raw_object)
        if api_response.status_code in (200, 202, 204):
            # successfully deleted
            self.raw_object = None
       else: ...???
```

But I don't understand what the raw_object is/does either so I might not really be qualified to change this code. (just wanted the delete functionality added) . The code could use some more documentation too (what does the api.registry do for example? seems interesting but I don't find any docs). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33)*

**Comment by maruqu** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[jsonapi_requests/orm/api_model.py, line 158 at r1](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-L0EtLQtxrpoMby54fWj:-L0P7hyv0m_ScN11XJLg:b-n86wff) ([raw file](https://github.com/socialwifi/jsonapi-requests/blob/5791b7f1635f588bc3c64572780726ef091779a4/jsonapi_requests/orm/api_model.py#L158)):*
<details><summary><i>Previously, thomaxxl (Thomas Pollet) wrote…</i></summary><blockquote>

The spec has the following to say regarding deleting resources:
<quote>
Responses
202 Accepted
If a deletion request has been accepted for processing, but the processing has not been completed by the time the server responds, the server MUST return a 202 Accepted status code.

204 No Content
A server MUST return a 204 No Content status code if a deletion request is successful and no content is returned.

200 OK
A server MUST return a 200 OK status code if a deletion request is successful and the server responds with only top-level meta data.

404 NOT FOUND
A server SHOULD return a 404 Not Found status code if a deletion request fails due to the resource not existing.

Other Responses
A server MAY respond with other HTTP status codes.

A server MAY include error details with error responses.

A server MUST prepare responses, and a client MUST interpret responses, in accordance with HTTP semantics. 
</quote>


Not sure what I should do in case of a 202 either
I may do something like this:

```
def delete(self):
        api_response = self.endpoint.delete(object=self.raw_object)
        if api_response.status_code in (200, 202, 204):
            # successfully deleted
            self.raw_object = None
       else: ...???
```

But I don't understand what the raw_object is/does either so I might not really be qualified to change this code. (just wanted the delete functionality added) . The code could use some more documentation too (what does the api.registry do for example? seems interesting but I don't find any docs). 
</blockquote></details>

Basically `raw_object` is the store(cache) for objects attributes, after successful delete,
we need to update the raw_object with proper data (in this situation the object is deleted, so there should be no data)

If we wouldn't do it, accessing any deleted object attribute, will search the raw object for this attribute and it will find it, because it the raw_object wasn't "synced" during the delete.

Also keep in mind the lazy nature od this library, accessing object's attributes causes requests only if the attribute wasn't found in the `raw_object` or when explicitly calling `refresh()`.

We are planing to add comprehensive documentation in near future.

---

*[tests/test_orm.py, line 343 at r2](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-L0P7SHItnmOKlXtyzgT:-L0P6M-IhJCtU-NkC4Ta:beo8we9) ([raw file](https://github.com/socialwifi/jsonapi-requests/blob/a16994ad12472948a306675a099229e3e82ee1cf/tests/test_orm.py#L343)):*
> ```Python
>         test.delete()
>         mock_api.endpoint.assert_called_with('test/123')
>         assert mock_api.endpoint.return_value.delete.call_count > 0
> ```

Great, thanks for the test!

Assertions should be as precise as possible, previous version was better.

Please change it to eg. `assert_called_once()` and your pull request will be ready to merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33)*

**Comment by thomaxxl** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/test_orm.py, line 343 at r2](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-L0P7SHItnmOKlXtyzgT:-L0PMDuSP8zZvaLmxH28:b-4j8pf5) ([raw file](https://github.com/socialwifi/jsonapi-requests/blob/a16994ad12472948a306675a099229e3e82ee1cf/tests/test_orm.py#L343)):*
assert_called_once and assert_called don't exist in "platform linux -- Python 3.5.2, pytest-3.3.1, py-1.5.2, pluggy-0.6.0". I changed th test to use call_count after github travis complained.

self = <MagicMock name='mock.endpoint().delete' id='139810643183488'>, name = 'assert_called_once'

    def __getattr__(self, name):
        if name in {'_mock_methods', '_mock_unsafe'}:
            raise AttributeError(name)
        elif self._mock_methods is not None:
            if name not in self._mock_methods or name in _all_magics:
                raise AttributeError("Mock object has no attribute %r" % name)
        elif _is_magic(name):
            raise AttributeError(name)
        if not self._mock_unsafe:
            if name.startswith(('assert', 'assret')):
>               raise AttributeError(name)
E               AttributeError: assert_called_once

/usr/lib/python3.5/unittest/mock.py:583: AttributeError
========================================= 1 failed, 27 passed in 0.63 seconds ==========================================

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33)*

**Comment by maruqu** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/test_orm.py, line 343 at r2](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-L0P7SHItnmOKlXtyzgT:-L0Q9X4KdwpvIpNMvGmy:bqdp059) ([raw file](https://github.com/socialwifi/jsonapi-requests/blob/a16994ad12472948a306675a099229e3e82ee1cf/tests/test_orm.py#L343)):*
<details><summary><i>Previously, thomaxxl (Thomas Pollet) wrote…</i></summary><blockquote>

assert_called_once and assert_called don't exist in "platform linux -- Python 3.5.2, pytest-3.3.1, py-1.5.2, pluggy-0.6.0". I changed th test to use call_count after github travis complained.

self = <MagicMock name='mock.endpoint().delete' id='139810643183488'>, name = 'assert_called_once'

    def __getattr__(self, name):
        if name in {'_mock_methods', '_mock_unsafe'}:
            raise AttributeError(name)
        elif self._mock_methods is not None:
            if name not in self._mock_methods or name in _all_magics:
                raise AttributeError("Mock object has no attribute %r" % name)
        elif _is_magic(name):
            raise AttributeError(name)
        if not self._mock_unsafe:
            if name.startswith(('assert', 'assret')):
>               raise AttributeError(name)
E               AttributeError: assert_called_once

/usr/lib/python3.5/unittest/mock.py:583: AttributeError
========================================= 1 failed, 27 passed in 0.63 seconds ==========================================


</blockquote></details>

oh, I'm sorry, I didn't catch that problem.
To stay precise just change the assertion condition from greater to equal and your Pull request will be ready to merge :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33)*

**Comment by maruqu** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-:-L0eb6GuDHIrithFFVyt:bkywwy7)*

**Comment by 5ghz** [comment]
There are any news about this pull request?

**Comment by maruqu** [comment]
Pull request is ready to merge, we will release new version in the following week 🎄

**Comment by jgoclawski** [comment]
Hi, thanks for the contribution and sorry for the delay!
I've made a few changes manually, so that this PR doesn't wait any longer. I've already merged it into master and will release it in a moment.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[jsonapi_requests/orm/api_model.py, line 158 at r1](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-L0EtLQtxrpoMby54fWj:-L2BdSZfjuXcFaWHEdQj:b-66ce3f) ([raw file](https://github.com/socialwifi/jsonapi-requests/blob/5791b7f1635f588bc3c64572780726ef091779a4/jsonapi_requests/orm/api_model.py#L158)):*
<details><summary><i>Previously, maruqu (Artur Mruk) wrote…</i></summary><blockquote>

Basically `raw_object` is the store(cache) for objects attributes, after successful delete,
we need to update the raw_object with proper data (in this situation the object is deleted, so there should be no data)

If we wouldn't do it, accessing any deleted object attribute, will search the raw object for this attribute and it will find it, because it the raw_object wasn't "synced" during the delete.

Also keep in mind the lazy nature od this library, accessing object's attributes causes requests only if the attribute wasn't found in the `raw_object` or when explicitly calling `refresh()`.

We are planing to add comprehensive documentation in near future.
</blockquote></details>

After second thought - it's better to not delete the local object and assume that the user knows it's been deleted. It's what ORM clients usually do, for example Django - https://docs.djangoproject.com/en/2.0/ref/models/instances/#deleting-objects or ember-data (reference JSON:API implementation).

I've modified the test, to reflect our assumptions about effects of deleting a model.

---

*[tests/test_orm.py, line 326 at r3](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-L2BeiiTdKJ_QExwSbpd:-L2BeiiTdKJ_QExwSbpe:b6cn47i) ([raw file](https://github.com/socialwifi/jsonapi-requests/blob/3ce03df692701b45500aa8d29f8fe44b45d28e71/tests/test_orm.py#L326)):*
> ```Python
>         assert result[0].other.name == 'alice'
> ```

Style: Two blank lines, I've removed one of them.
Will try to configure flake8, so that our style-guide is automatically communicated to contributors.

---

*[tests/test_orm.py, line 329 at r3](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-L2Bf-kcK7d8BbjjibWH:-L2Bf-kcK7d8BbjjibWI:b-xnl9x2) ([raw file](https://github.com/socialwifi/jsonapi-requests/blob/3ce03df692701b45500aa8d29f8fe44b45d28e71/tests/test_orm.py#L329)):*
> ```Python
>     def test_delete(self):
>         mock_api = mock.MagicMock()
>         mock_api.endpoint.return_value.get.return_value.content.data = data.JsonApiObject(
> ```

This mock was unused, I've removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/33#-:-L2Bf8cyKhri5a2auG6R:b54puei)*

**Comment by jgoclawski** [comment]
Released as version 0.6.0.

**Pull request closed without merging**
