### PR TITLE
Fix to many relationships.

### LINKED ISSUE #18: orm module cannot be imported
Add this to jsonapi_requests/__init__.py:

```
from .orm import OrmApi

__all__ = [Api, JsonApiObject, OrmApi]
```

### LINKED ISSUE #19: Can't use related field
After applying #18, I still can't use a RelationField.

```python
class Design(orm.ApiModel):
    class Meta:
        type = 'designs'
        api = api

    name = orm.AttributeField('name')
    sub_designs = orm.RelationField('sub_designs')

design  = Design.from_id(1)
print(design.name)

>>> AttributeError: 'JsonApiObject' object has no attribute 'name'
```

Commenting out the sub_designs line, I can print out the design name as expected.

### PR DESCRIPTION
**Pull request by kramarz**
Closes #18
Closes #19
We probably need more tests of orm in future.

---
This change is [Reviewable](https://reviewable.io/reviews/socialwifi/jsonapi-requests/20)

### CODE REVIEW

**Comment by jgoclawski** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 8 at r5](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/20#-Khgb-hzIic-SWsM6bol:-Khgb-hzIic-SWsM6bom:brpifb2) ([raw file](https://github.com/socialwifi/jsonapi-requests/blob/e66f1f8c64d5d663a4a2e42eaf870ea67da300d4/CHANGELOG.md#L8)):*
> ```Markdown
> 
> - Basic support for to many relationship in orm.
> - Include orm in jsonapi-requests import.
> ```

how about updating the README? An explicit import line at the beginning would make it easier to use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/20)*

**Comment by jgoclawski** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/20)*

**Comment by evandavey** [comment]
Seems to work for me, thanks!

**Comment by kramarz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[CHANGELOG.md, line 8 at r5](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/20#-Khgb-hzIic-SWsM6bol:-Ki44zvsOYlZNFmCws5U:b-896fix) ([raw file](https://github.com/socialwifi/jsonapi-requests/blob/e66f1f8c64d5d663a4a2e42eaf870ea67da300d4/CHANGELOG.md#L8)):*
<details><summary><i>Previously, jgoclawski (Jakub Gocławski) wrote…</i></summary><blockquote>

how about updating the README? An explicit import line at the beginning would make it easier to use.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/20)*

**Comment by jgoclawski** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/jsonapi-requests/20#-:-Ki4D2e8zEwi7IsdJJJg:bnfp4nl)*

**Pull request merged**
